# Generated by Django 5.1 on 2024-10-22 17:37
from django.db import migrations


def add_initial_data(apps, schema_editor):
    Task = apps.get_model('task', 'Task')
    Tag = apps.get_model('task', 'Tag')
    Project = apps.get_model('task', 'Project')

    Task.objects.all().delete()

    high = Tag.objects.create(title='High Priority')
    medium = Tag.objects.create(title='Medium Priority')
    low = Tag.objects.create(title='Low Priority')
    feature = Tag.objects.create(title='Feature')
    bug = Tag.objects.create(title='Bug')

    task1 = Task.objects.create(title="Create Django Application", description="Setting up Django project.")
    task2 = Task.objects.create(title="Create Django Models", description="Migrate models to database.")
    task3 = Task.objects.create(title="Create Django Views", description="Create templates to views.")
    task4 = Task.objects.create(title="Start Task Management Project",
                                description="Plan and start working on the project.")
    task5 = Task.objects.create(title="Setup docker image", description="Create Dockerfile and docker-compose")

    task1.tags.add(high, feature)
    task2.tags.add(medium, feature)
    task3.tags.add(low, bug)
    task4.tags.add(high, feature)
    task5.tags.add(medium, bug)

    project1 = Project.objects.create(title='Project Django', description='Django project.')
    project1.tasks.add(task1, task2, task3)

    project2 = Project.objects.create(title='Project Docker', description='Docker project.')
    project2.tasks.add(task4, task5)


class Migration(migrations.Migration):
    dependencies = [
        ('task', '0003_tag_project_task_tags'),
    ]

    operations = [
        migrations.RunPython(add_initial_data),
    ]
